env:
  TERM: alacritty
window:
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  decorations: full
  startup_mode: Windowed
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: Ubuntu Mono
    style: Regular
  bold:
    family: Ubuntu Mono
    style: Medium
  italic:
    family: Ubuntu Mono
    style: Italic
  size: 12
  offset:
    x: 0
    y: 3
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
hide_cursor_when_typing: true
live_config_reload: true

# Base16 Solarized Dark 256 - alacritty color config
# Ethan Schoonover (modified by aramisgithub)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x93a1a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x002b36'
    cursor: '0x93a1a1'

  # Normal colors
  normal:
    black:   '0x002b36'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0x6c71c4'
    cyan:    '0x2aa198'
    white:   '0x93a1a1'

  # Bright colors
  bright:
    black:   '0x657b83'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0x6c71c4'
    cyan:    '0x2aa198'
    white:   '0xfdf6e3'

  indexed_colors:
    - { index: 16, color: '0xcb4b16' }
    - { index: 17, color: '0xd33682' }
    - { index: 18, color: '0x073642' }
    - { index: 19, color: '0x586e75' }
    - { index: 20, color: '0x839496' }
    - { index: 21, color: '0xeee8d5' }
mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true
