theme = "onedark"

[editor]
line-number = "relative"
mouse = false
cursorline = true
auto-completion = true
auto-save = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode


[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1
